### ISSUE TITLE
Python 2.7.9 requirement too restrictive for CentOS 7

### ISSUE THREAD

**Issue by cro** [HewlettPackard/python-hpOneView#279]
I note that in version 3.2.1 of the Python hpOneView library that a check is made at module start to verify that the running Python is at least version 2.7.9.  I assume this is because the SSL support was retooled in 2.7.9 to support certificate validation.  However, Python 2.7.9 is not available in CentOS 7; the system Python is 2.7.5.  Furthermore, the newer SSL stack was backported by RedHat from 2.7.9 to 2.7.5 for this distribution.  Would you consider a PR to make this check more specific so that the default system Python on Cent7 can be used with python-hpOneView?

**Comment by bsoutham** [comment]
Good to hear from you C.R.
We'll look and see if there is something we can do here.

**Comment by fgbulsoni** [comment]
Hey @cro , thank you very much for the feedback.

With PR #275 we've actually changed all `raise` calls for `warning` calls, so it should be possible to use the SDK despite of being on a Python version bellow 2.7.9 as long as the requirements are met (as you mentioned, SSL support is one). 

You'll receive a warning that you are on an unsupported version and you can probably ignore that since your version has SSL backported.

Are you being blocked by the check in some way?

**Comment by cro** [comment]
No, I cheat, and just changed the check to 2.7.5 for this particular effort. :-)

I'll record that in the README for our OneView integration, though.  Thanks!  I'll close this ticket.
