### ISSUE TITLE
Feature request -- allow updating of single custom attribute instead of whole list

### ISSUE THREAD

**Issue by kmullican** [HewlettPackard/python-hpOneView#305]
### Scenario/Intent
I wolud like to be able to update select custom attributes in a profile instead of having to update the entire list of custom attributes.  Sometimes an OS Plan Script can have many custom attributes, so this woud be a nice feature.

### Environment Details
 - **OneView SDK Version:** 3.3.0
 - **OneView Appliance Version:** 3.10.04-0299553
 - **OneView Client API Version:** 500
 - **Python Version:** 3.4.5
 - **Platform:** CentOS 7.3 x86_64

### Steps to Reproduce
Create a profile with an OS Deployment Plan that requires 3 custom attributes named 'key1', 'key2', and 'key3' with corresponding values 'value1', 'value2', and 'value3'
Update the profile with Python SDK and change the 'key2' custom attributes to have value of 'new2':
oneview_client = OneViewClient.from_json_file('connection.json')
profile_to_update['osDeploymentSettings']['osCustomAttributes'] = dict(name='key2',value='new2')
profile_updated = oneview_client.server_profiles.update(resource=profile_to_update, id_or_uri=profile_to_update['uri'])

### Expected Result
The resulting profile would have all custom attributes left unchanged, except the attribute 'key2', which would have the value 'new2'

### Actual Result
No custom attributes are changed.  In order to change 'key2' custom attribute, all custom attributes have to be supplied, like:
profile_to_update['osDeploymentSettings']['osCustomAttributes'] = dict(name='key1',value='value1'),dict(name='key2',value='new2'),dict(name='key3',value='key3')

**Comment by fgbulsoni** [comment]
Issue here seems to be that server_profile['osDeploymentSettings']['osCustomAttributes'] is a `list` of `dicts`, so its indexes would actually be numbers.

In the case presented:
```Python
profile_to_update['osDeploymentSettings']['osCustomAttributes'] = dict(name='key2',value='new2')
profile_updated = oneview_client.server_profiles.update(resource=profile_to_update, id_or_uri=profile_to_update['uri'])
```

This first line is actively rewriting **all** the contents of `profile_to_update['osDeploymentSettings']['osCustomAttributes']` to match the new value of `dict(name='key2',value='new2')`.

Changing only the second value could be achieved by pointing to the specific position we want changed, 1 in this case, since lists start at 0:

```Python
profile_to_update['osDeploymentSettings']['osCustomAttributes'][1] = dict(name='key2',value='new2')
```

A *worse* case is when we aren't sure which position we actually want to change, just the value of the key. 

In that case, one option is to iterate through each item of the list and if the key matches what we want, we alter the value referenced by that key:

```Python
>>> my_list
[{'name': 'key1', 'value': 'value1'}, {'name': 'key2', 'value': 'value2'}, {'name': 'key3', 'value': 'value3'}]
>>> for i in my_list:
...     if i['name'] is 'key2':
...             i['value'] = 'new_value'
...
>>> my_list
[{'name': 'key1', 'value': 'value1'}, {'name': 'key2', 'value': 'new_value'}, {'name': 'key3', 'value': 'value3'}]
```

So, for now "updating select custom attributes" can be achieved in relatively straightforward ways. Not entirely sure how much benefit a helper method would bring.

**Comment by fgbulsoni** [comment]
This issue has been idle for a while and it appears to be resolved by this [comment](https://github.com/HewlettPackard/python-hpOneView/issues/305#issuecomment-330203834), so I'm closing it down. 
If this is still an issue, it should be reopened or referenced through a new issue.
